spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8000
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
logging:
  file: ecommerce.log

domain: http://localhost:8000
user:
  activation:
    token-availability-hours: 24
