spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 793ab7001@smtp-brevo.com
    password: KWpOm64CLJ5XGTy3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8000
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
logging:
  file: ecommerce.log

domain: http://localhost:8000
user:
  activation:
    token-availability-hours: 24
